# Generated by Django 4.2.7 on 2023-11-22 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bapp', '0001_initial'),
    ]

    operations = [
    ]
