# Generated by Django 4.2.7 on 2023-11-22 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bapp', '0002_auto_20231122_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image_url',
        ),
    ]
