# Generated by Django 4.2.7 on 2023-11-29 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bapp', '0009_remove_review_book_remove_review_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookrent',
            old_name='user',
            new_name='email_id',
        ),
    ]
