# Generated by Django 4.2.7 on 2023-11-29 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bapp', '0010_rename_user_bookrent_email_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookrent',
            old_name='email_id',
            new_name='user',
        ),
    ]
