# Generated by Django 4.2.7 on 2023-11-29 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bapp', '0011_rename_email_id_bookrent_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user',
            new_name='username',
        ),
    ]
